import type { Config } from "./types.js";

export function generateEnvExample(config: Config): string {
  const lines: string[] = [];
  const vars = config.vars;

  for (const [name, spec] of Object.entries(vars)) {
    if (spec.description) {
      lines.push(`# ${spec.description}`);
    }
    if (spec.default !== undefined) {
      lines.push(`# ${name}=${spec.default}`);
      if (spec.required) {
        lines.push(`# ^^^ REQUIRED: uncomment and set this value`);
      }
    } else if (spec.required) {
      lines.push(`${name}=`);
    } else {
      lines.push(`# ${name}=`);
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}

export function generateTypeScriptTypes(config: Config): string {
  const lines: string[] = [
    "// Auto-generated by checkmyenv",
    "// https://github.com/amitwaks/checkmyenv",
    "",
    "export interface Env {",
  ];

  for (const [name, spec] of Object.entries(config.vars)) {
    const tsType = spec.type === "number" ? "number"
      : spec.type === "integer" ? "number"
      : spec.type === "boolean" ? "boolean"
      : "string";

    const optional = spec.required !== true && spec.default === undefined ? "?" : "";
    const doc = spec.description ? `  // ${spec.description}` : "";
    if (doc) lines.push(doc);
    lines.push(`  readonly ${name}${optional}: ${tsType};`);
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
